### ISSUE TITLE
threefold/gridproxy v1.0.0

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/crystallib#242]
> branch ```development_gridproxy```

this is only a client to the proxy, to fetch information from the grid

## requirements

- good examples
- get all relevant information from gridproxy

**Comment by 0oM4R** [comment]
WIP: I just had an overview of that project and fixed some imports and build warnings.
I will create the examples next week isA

**Comment by 0oM4R** [comment]
WIP:
- update some imports and filters
- I added examples for 
    - Nodes
    - get all nodes
    - get nodes with some prop of NodeFilter
    - get node iteration 
    - get node status by id
    - get node by available resources 
    
    - gateway :
    -  get all gateway nodes 
    - get gateway with some prop of GatewayFilter
    - get gateway by node id
    - get gateway iteration 
    
    - Farm :
    -  get all farms 
    - get farm with some  prop FarmFilter
    - get farm iteration 
    
    - twin :
    -  get all twins 
    - get twin with some  prop TwinFilter
    - get twin iteration 
    
    - stats :
    - get grid stats for online nodes and all nodes
    
    - contracts: 
      - get all contracts
      - get contracts with some prop of ContractsFilter
      - get contracts iteration 
  
  Will add node statistics, ping, pgu , and will try to update the readme

**Comment by 0oM4R** [comment]
all mentioned examples are ready and i create a pr #266 but got a comment, working on it

**Comment by 0oM4R** [comment]
WIP: applied the required changes on most of example files, the remaining one is node examples.

**Comment by ashraffouda** [comment]
https://github.com/freeflowuniverse/crystallib/pull/266/files
