### ISSUE TITLE
stabilize markdown parser, ...

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/crystallib#304]
source is now  on branch development_db, lets develop on development_markdown

- crystallib/data/markdownparser
   - needs to be finish 
- crystallib/core/texttools/multiline.v (works ok I think)
- crystallib/data/paramsparser (works ok I think)
   - lets check the tests
- crystallib/data/actionparser (works ok I think)
   - lets check tests and create some more

**Comment by ashraffouda** [comment]
for codeblocks it was like this 
```
if mut llast is elements.CodeBlock {
			if line.starts_with('```') || line.starts_with('"""') || line.starts_with("'''") {
				parser.next_start()
				continue
			} else {
				llast.content += '${line}\n'
			}
			parser.next()
			continue
		}
```
this will cause errors in some languages like [here](https://github.com/freeflowuniverse/crystallib/blob/development_db/crystallib/data/markdownparser/testdata/test.md) in the example will result in a totally wrong value so I removed it also code blocks in markdown uses ```

**Comment by MarioBassem** [comment]
progress update:
- small fixes in document markdown method
- added assertion that generated markdown is the same with the same element input

**Comment by despiegk** [comment]
> here

hmmm, not sure this is the right decision, lets review

**Comment by MarioBassem** [comment]
progress update:
- currently, supported elements are: actions, codeblocks, comments, headers, html, include, paragraph, table
- parser's output is deterministic

**Comment by MarioBassem** [comment]
some issues:
- currently, current implementation of the parser does the parsing line by line, so any two elements that span the same line are not read correctly. an example:
```
<html>content</html> <html>
     ....
</html>
```
this will be treated as one html element.
- also, i have no notion of what a `none` or `text` element are supposed to do.

@despiegk do you have any input on this please?

**Comment by MarioBassem** [comment]
progress update:
- for texttools/multiline, i got that the purpose of this is to squash multiple lines into one, while separating content from comments, i don't really get why though.
- i found a few bugs in comment start detection and `multiline` start checks, i added tests that cover these case
- i don't really get what are `multilines`, if it is just quoted text that spans multiple lines, then why do we assume it must start with `:'`, `:"`, `:'''`, or `:"""` ? is this generated text that will always have this specification?

**Comment by MarioBassem** [comment]
progress update:
- added tests and fixes for most of paramsparser module's functionality
- resp related methods in paramsparser are buggy, added a test to cover them but still haven't fixed the methods

**Comment by MarioBassem** [comment]
progress update:
- added tests and fixes for actionparser

note:
i added some tests for the `multiline_to_single` method in texttools, i believe these tests cover some unhandled cases, but i didn't fix them as i don't really know how this tool is intended to work, so i believe it needs to be reviewed.
the tests are here: https://github.com/freeflowuniverse/crystallib/pull/306/files#diff-1e38d60d8e046eeee9f8dbfb9f46efaee212789f8ddf3f464b136ccd88801bff
